GET http://localhost:4000/questions

###
POST  http://localhost:4000/question
Content-Type: application/json

{
    "name": "2 + 2",
    "optionOne": "A",
    "optionTwo": "B",
    "optionThree": "C",
    "answer": "B",
    "level": "Beginner"
}

###
DELETE http://localhost:4000/question/07809723-12b7-4e7b-96c0-31aa30687a4d
