GET http://localhost:4000/siswas

###
POST http://localhost:4000/siswa
Content-Type: application/json

{
    "name": "Jonathan Rompas"
}

###
DELETE http://localhost:4000/siswa/55c2fe22-dc36-4403-aa8e-8a241369f2bd